name: borktok
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.9.3
  provider: ^6.1.2
  http: ^0.13.5
  fl_chart: ^0.70.2
  dash_chat_2: ^0.0.21
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2+4
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
